"""programs, csv submissions, school display fields

Revision ID: 0a8466af6e5e
Revises: 0002_person_category
Create Date: 2026-09-13 13:34:33.179288
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0a8466af6e5e'
down_revision = '0002_person_category'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_submissions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'rejected', name='submission_status', native_enum=False), nullable=False),
    sa.Column('rows', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('submitted_by', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_submissions_status', 'csv_submissions', ['status', 'created_at'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('specialty', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('program_type', sa.String(length=64), nullable=True),
    sa.Column('start_url', sa.Text(), nullable=True),
    sa.Column('directory_url', sa.Text(), nullable=True),
    sa.Column('people_count', sa.Integer(), nullable=False),
    sa.Column('resident_count', sa.Integer(), nullable=False),
    sa.Column('fellow_count', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'specialty', name='uq_programs_site_specialty')
    )
    op.create_index('ix_programs_site', 'programs', ['site_id'], unique=False)
    op.add_column('records', sa.Column('program_id', sa.String(length=64), nullable=True))
    op.create_index('ix_records_program', 'records', ['program_id'], unique=False)
    op.create_foreign_key(None, 'records', 'programs', ['program_id'], ['id'], ondelete='SET NULL')
    op.add_column('sites', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('location', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'location')
    op.drop_column('sites', 'name')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_index('ix_records_program', table_name='records')
    op.drop_column('records', 'program_id')
    op.drop_index('ix_programs_site', table_name='programs')
    op.drop_table('programs')
    op.drop_index('ix_submissions_status', table_name='csv_submissions')
    op.drop_table('csv_submissions')
    # ### end Alembic commands ###
