"""screenshot dimensions

Revision ID: 9e36696d05e8
Revises: 0a8466af6e5e
Create Date: 2026-09-13 13:48:53.847648
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '9e36696d05e8'
down_revision = '0a8466af6e5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record_versions', sa.Column('screenshot_width', sa.Integer(), nullable=True))
    op.add_column('record_versions', sa.Column('screenshot_height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record_versions', 'screenshot_height')
    op.drop_column('record_versions', 'screenshot_width')
    # ### end Alembic commands ###
