"""initial schema

Revision ID: edea3953720a
Revises: 
Create Date: 2026-09-11 22:46:14.789584
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'edea3953720a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'expired', name='export_status', native_enum=False), nullable=False),
    sa.Column('filters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('include_provenance', sa.Boolean(), nullable=False),
    sa.Column('include_emailed_column', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exports_status', 'exports', ['status', 'created_at'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'cancelled', 'stopped_at_limit', 'failed', name='run_status', native_enum=False), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stop_reason', sa.Enum('max_records', 'max_spend', 'cancelled', 'run_timeout', name='stop_reason', native_enum=False), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sites_total', sa.Integer(), nullable=False),
    sa.Column('sites_completed', sa.Integer(), nullable=False),
    sa.Column('sites_skipped', sa.Integer(), nullable=False),
    sa.Column('sites_failed', sa.Integer(), nullable=False),
    sa.Column('sites_rejected', sa.Integer(), nullable=False),
    sa.Column('records_found', sa.Integer(), nullable=False),
    sa.Column('records_new', sa.Integer(), nullable=False),
    sa.Column('records_changed', sa.Integer(), nullable=False),
    sa.Column('records_missing', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.BigInteger(), nullable=False),
    sa.Column('tokens_out', sa.BigInteger(), nullable=False),
    sa.Column('spend_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_status_created', 'runs', ['status', 'created_at'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('root_domain', sa.String(length=253), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('hospital_name', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.Enum('pending', 'post_secondary', 'k12_rejected', 'unreachable', 'unknown', name='validation_status', native_enum=False), nullable=False),
    sa.Column('validation_reason', sa.Text(), nullable=True),
    sa.Column('institution_type', sa.String(length=64), nullable=True),
    sa.Column('dominant_specialty', sa.String(length=128), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fingerprint', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_domain')
    )
    op.create_index('ix_sites_last_scraped_at', 'sites', ['last_scraped_at'], unique=False)
    op.create_table('known_paths',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avg_records', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'url_hash', name='uq_known_paths_site_url')
    )
    op.create_index('ix_known_paths_site_active', 'known_paths', ['site_id', 'is_active', 'score'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('identity_key', sa.String(length=320), nullable=False),
    sa.Column('identity_kind', sa.Enum('email', 'name', name='identity_kind', native_enum=False), nullable=False),
    sa.Column('role_account', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('role', sa.Enum('resident', 'fellow', 'unknown', name='record_role', native_enum=False), nullable=False),
    sa.Column('specialty_normalized', sa.String(length=128), nullable=True),
    sa.Column('specialty_raw', sa.Text(), nullable=True),
    sa.Column('pgy_at_capture', sa.Integer(), nullable=True),
    sa.Column('pgy_capture_date', sa.Date(), nullable=True),
    sa.Column('pgy_source', sa.Enum('extracted', 'derived', name='pgy_source', native_enum=False), nullable=True),
    sa.Column('class_of', sa.Integer(), nullable=True),
    sa.Column('class_of_source', sa.Enum('extracted', 'derived', name='class_of_source', native_enum=False), nullable=True),
    sa.Column('status', sa.Enum('active', 'new', 'changed', 'missing', name='record_status', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('current_version_id', sa.String(length=64), nullable=True),
    sa.Column('version_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('missing_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'identity_key', name='uq_records_site_identity')
    )
    op.create_index('ix_records_class_of', 'records', ['class_of'], unique=False)
    op.create_index('ix_records_email', 'records', ['email'], unique=False)
    op.create_index('ix_records_last_changed', 'records', ['last_changed_at'], unique=False)
    op.create_index('ix_records_last_seen', 'records', ['last_seen_at'], unique=False)
    op.create_index('ix_records_role', 'records', ['role'], unique=False)
    op.create_index('ix_records_site_status', 'records', ['site_id', 'status'], unique=False)
    op.create_index('ix_records_specialty', 'records', ['specialty_normalized'], unique=False)
    op.create_table('site_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'skipped', 'failed', 'rejected', 'cancelled', name='site_run_status', native_enum=False), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('force_rescan', sa.Boolean(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('steps_taken', sa.Integer(), nullable=False),
    sa.Column('step_budget', sa.Integer(), nullable=False),
    sa.Column('skip_reason', sa.Enum('unchanged_fingerprint', 'similarity_threshold', name='skip_reason', native_enum=False), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('records_found', sa.Integer(), nullable=False),
    sa.Column('records_new', sa.Integer(), nullable=False),
    sa.Column('records_changed', sa.Integer(), nullable=False),
    sa.Column('records_missing', sa.Integer(), nullable=False),
    sa.Column('known_path_hits', sa.Integer(), nullable=False),
    sa.Column('candidates_considered', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.BigInteger(), nullable=False),
    sa.Column('tokens_out', sa.BigInteger(), nullable=False),
    sa.Column('spend_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('checkpoint_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'site_id', name='uq_site_runs_run_site')
    )
    op.create_index('ix_site_runs_run_status', 'site_runs', ['run_id', 'status'], unique=False)
    op.create_index('ix_site_runs_site', 'site_runs', ['site_id'], unique=False)
    op.create_table('record_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('changed_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('page_title', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.Text(), nullable=True),
    sa.Column('screenshot_available', sa.Boolean(), nullable=False),
    sa.Column('screenshot_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extraction_method', sa.Enum('known_path', 'discovery', 'agent_nav', name='extraction_method', native_enum=False), nullable=False),
    sa.Column('fetch_mode', sa.Enum('html', 'render', 'both', name='fetch_mode_v', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('field_locations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('site_run_id', sa.String(length=64), nullable=True),
    sa.CheckConstraint('version_no > 0', name='ck_version_no_positive'),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'version_no', name='uq_version_record_no')
    )
    op.create_index('ix_versions_captured', 'record_versions', ['captured_at'], unique=False)
    op.create_index('ix_versions_record', 'record_versions', ['record_id', 'version_no'], unique=False)
    op.create_index('ix_versions_screenshot_expiry', 'record_versions', ['screenshot_expires_at'], unique=False)
    op.create_table('site_run_visits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('site_run_id', sa.String(length=64), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('fetch_mode', sa.Enum('html', 'render', 'both', name='fetch_mode', native_enum=False), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('records_yielded', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_run_id'], ['site_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_run_id', 'url_hash', name='uq_visit_site_run_url')
    )
    # ### end Alembic commands ###

    # Free-text search across the fields the /records `q` filter targets.
    # A functional GIN index keeps this a single migration with no extra column
    # to keep in sync on every write.
    op.execute(
        """
        CREATE INDEX ix_records_fts ON records
        USING GIN (
            to_tsvector(
                'simple',
                coalesce(full_name, '') || ' ' ||
                coalesce(email, '') || ' ' ||
                coalesce(specialty_normalized, '') || ' ' ||
                coalesce(specialty_raw, '')
            )
        )
        """
    )
    # Trigram index for substring/typeahead matching on names and hospitals.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        "CREATE INDEX ix_records_name_trgm ON records USING GIN (full_name gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_sites_domain_trgm ON sites USING GIN (root_domain gin_trgm_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_sites_domain_trgm")
    op.execute("DROP INDEX IF EXISTS ix_records_name_trgm")
    op.execute("DROP INDEX IF EXISTS ix_records_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_run_visits')
    op.drop_index('ix_versions_screenshot_expiry', table_name='record_versions')
    op.drop_index('ix_versions_record', table_name='record_versions')
    op.drop_index('ix_versions_captured', table_name='record_versions')
    op.drop_table('record_versions')
    op.drop_index('ix_site_runs_site', table_name='site_runs')
    op.drop_index('ix_site_runs_run_status', table_name='site_runs')
    op.drop_table('site_runs')
    op.drop_index('ix_records_specialty', table_name='records')
    op.drop_index('ix_records_site_status', table_name='records')
    op.drop_index('ix_records_role', table_name='records')
    op.drop_index('ix_records_last_seen', table_name='records')
    op.drop_index('ix_records_last_changed', table_name='records')
    op.drop_index('ix_records_email', table_name='records')
    op.drop_index('ix_records_class_of', table_name='records')
    op.drop_table('records')
    op.drop_index('ix_known_paths_site_active', table_name='known_paths')
    op.drop_table('known_paths')
    op.drop_index('ix_sites_last_scraped_at', table_name='sites')
    op.drop_table('sites')
    op.drop_index('ix_runs_status_created', table_name='runs')
    op.drop_table('runs')
    op.drop_index('ix_exports_status', table_name='exports')
    op.drop_table('exports')
    # ### end Alembic commands ###
